using Microsoft.Xna.Framework.Input;
using System.Collections.Generic;

namespace Game.Jam.StreetRaceFate.Engine.Services;
public interface IKeysService
{
    List<Keys> GetValidKeys();
    string GetKeyString(Keys key);
}
public class KeysService : IKeysService
{
    public List<Keys> GetValidKeys()
    {
        return new List<Keys>
        {
            Keys.Escape,
            Keys.F1,
            Keys.F2,
            Keys.F3,
            Keys.F4,
            Keys.F5,
            Keys.F6,
            Keys.F7,
            Keys.F8,
            Keys.F9,
            Keys.F10,
            Keys.F11,
            Keys.F12,
            Keys.Pause,

            Keys.OemTilde,
            Keys.D1,
            Keys.D2,
            Keys.D3,
            Keys.D4,
            Keys.D5,
            Keys.D6,
            Keys.D7,
            Keys.D8,
            Keys.D9,
            Keys.D0,
            Keys.OemMinus,
            Keys.OemPlus,
            Keys.Back,
            Keys.Insert,
            Keys.Home,
            Keys.PageUp,
            Keys.Divide,
            Keys.Multiply,
            Keys.Subtract,

            Keys.Tab,
            Keys.Q,
            Keys.W,
            Keys.E,
            Keys.R,
            Keys.T,
            Keys.Y,
            Keys.U,
            Keys.I,
            Keys.O,
            Keys.P,
            Keys.OemOpenBrackets,
            Keys.OemCloseBrackets,
            Keys.OemPipe,
            Keys.Delete,
            Keys.End,
            Keys.PageDown,
            Keys.NumPad7,
            Keys.NumPad8,
            Keys.NumPad9,
            Keys.Add,

            Keys.A,
            Keys.S,
            Keys.D,
            Keys.F,
            Keys.G,
            Keys.H,
            Keys.J,
            Keys.K,
            Keys.L,
            Keys.OemSemicolon,
            Keys.OemQuotes,
            Keys.Enter,
            Keys.NumPad4,
            Keys.NumPad5,
            Keys.NumPad6,

            Keys.Z,
            Keys.X,
            Keys.C,
            Keys.V,
            Keys.B,
            Keys.N,
            Keys.M,
            Keys.OemComma,
            Keys.OemPeriod,
            Keys.OemQuestion,
            Keys.Up,
            Keys.NumPad1,
            Keys.NumPad2,
            Keys.NumPad3,

            Keys.LeftControl,
            Keys.Space,
            Keys.RightControl,
            Keys.Left,
            Keys.Down,
            Keys.Right,
            Keys.NumPad0,
        };
    }

    public string GetKeyString(Keys key)
    {
        return key switch
        {
            Keys.Escape => "Esc",
            Keys.F1 => "F1",
            Keys.F2 => "F2",
            Keys.F3 => "F3",
            Keys.F4 => "F4",
            Keys.F5 => "F5",
            Keys.F6 => "F6",
            Keys.F7 => "F7",
            Keys.F8 => "F8",
            Keys.F9 => "F9",
            Keys.F10 => "F10",
            Keys.F11 => "F11",
            Keys.F12 => "F12",
            Keys.Pause => "Pse",

            Keys.OemTilde => "~",
            Keys.D1 => "1",
            Keys.D2 => "2",
            Keys.D3 => "3",
            Keys.D4 => "4",
            Keys.D5 => "5",
            Keys.D6 => "6",
            Keys.D7 => "7",
            Keys.D8 => "8",
            Keys.D9 => "9",
            Keys.D0 => "0",
            Keys.OemMinus => "_",
            Keys.OemPlus => "=",
            Keys.Back => "Back",
            Keys.Insert => "Ins",
            Keys.Home => "Home",
            Keys.PageUp => "PgUp",
            Keys.Divide => "/",
            Keys.Multiply => "*",
            Keys.Subtract => "-",

            Keys.Tab => "Tab",
            Keys.Q => "Q",
            Keys.W => "W",
            Keys.E => "E",
            Keys.R => "R",
            Keys.T => "T",
            Keys.Y => "Y",
            Keys.U => "U",
            Keys.I => "I",
            Keys.O => "O",
            Keys.P => "P",
            Keys.OemOpenBrackets => "[",
            Keys.OemCloseBrackets => "]",
            Keys.OemPipe => "|",
            Keys.Delete => "Del",
            Keys.End => "End",
            Keys.PageDown => "PgDw",
            Keys.NumPad7 => "np7",
            Keys.NumPad8 => "np8",
            Keys.NumPad9 => "np9",
            Keys.Add => "+",

            Keys.A => "A",
            Keys.S => "S",
            Keys.D => "D",
            Keys.F => "F",
            Keys.G => "G",
            Keys.H => "H",
            Keys.J => "J",
            Keys.K => "K",
            Keys.L => "L",
            Keys.OemSemicolon => ";",
            Keys.OemQuotes => "\"",
            Keys.Enter => "Ent",
            Keys.NumPad4 => "np4",
            Keys.NumPad5 => "np5",
            Keys.NumPad6 => "np6",

            Keys.Z => "Z",
            Keys.X => "X",
            Keys.C => "C",
            Keys.V => "V",
            Keys.B => "B",
            Keys.N => "N",
            Keys.M => "M",
            Keys.OemComma => ",",
            Keys.OemPeriod => ".",
            Keys.OemQuestion => "?",
            Keys.Up => "Up",
            Keys.NumPad1 => "np1",
            Keys.NumPad2 => "np2",
            Keys.NumPad3 => "np3",

            Keys.LeftControl => "Lctr",
            Keys.Space => "Space",
            Keys.RightControl => "Rctr",
            Keys.Left => "Left",
            Keys.Down => "Down",
            Keys.Right => "Right",
            Keys.NumPad0 => "np0",

            _ => "unkown"
        };
    }
}
